[phases.setup]
nixPkgs = [
  "cairo",
  "pango", 
  "libjpeg",
  "giflib",
  "librsvg",
  "pixman",
  "pkg-config"
]

[phases.build]
cmds = [
  "npm ci",
  "npm rebuild canvas --build-from-source",
  "npm run compile"
]
